"""Builder node — executes tasks via Cline CLI inside Docker containers."""

from __future__ import annotations

import json
import logging
import shlex
import time

from orchestrator.config import settings
from orchestrator.docker_engine.manager import ContainerManager
from orchestrator.execution_contract import count_contract_progress, normalize_execution_contract
from orchestrator.graph.state import AutomatronState
from orchestrator.llm.configuration import default_llm_config, normalize_llm_config
from orchestrator.llm.prompts import load_prompt
from orchestrator.observability import trace_event
from orchestrator.plan_parser.parser import get_global_rules

logger = logging.getLogger(__name__)

container_manager = ContainerManager()

# ---------------------------------------------------------------------------
# Builder prompt templates — separated into composable sections so that
# universal rules, stack-specific rules, and task context are independent.
# ---------------------------------------------------------------------------

_PROMPT_HEADER = (
    "You are Automatron Builder operating inside the project workspace.\n"
)

_PROMPT_UNIVERSAL_RULES = (
    "- Keep PLAN.md in sync with completed tasks\n"
    "- Do not remove the existing git repository\n"
    "- Preserve the generated GitHub Actions workflows unless intentionally updating them\n"
    "- Do not access external deployment credentials\n"
    "- Do not start long-running foreground processes like `next dev`, `npm run dev`, `vite`, "
    "or database studios unless the current task explicitly requires a preview server\n"
    "- For verification during normal build tasks, prefer one-shot commands like `npm run build`, "
    "`npm run lint`, route-level tests, or commands wrapped with `timeout`\n"
)

_PROMPT_DEPLOY_ARTIFACTS = (
    "- By the end of the plan, the repo must contain Dockerfile, .env.example, "
    "deploy/docker-compose.yml, DEPLOY.md, .github/workflows/ci.yml, "
    "and .github/workflows/deploy.yml. Preview must be able to run on the allocated port.\n"
)

_PROMPT_NEXTJS_RULES = (
    "- Expose a GET `/api/health` endpoint that returns JSON and verifies core dependencies "
    "such as the database when they exist\n"
    "- Replace default scaffold metadata like `Create Next App` and `Generated by create next app` "
    "with project-specific title and description\n"
)

_PROMPT_PRISMA_RULES = (
    "- Inspect the installed Prisma major version before changing Prisma setup\n"
    "- For Prisma 5 projects, keep a valid `url` inside the `datasource db` block in "
    "`prisma/schema.prisma`\n"
    "- For Prisma 7 projects, create `prisma.config.ts` or `prisma.config.js` in `/workspace`, "
    "never in `/workspace/prisma`\n"
    "- When creating Prisma 7 config, import `defineConfig` from `prisma/config`, not "
    "`@prisma/internals`\n"
)


def _is_deploy_relevant_task(task_text: str, completed_tasks: int, total_tasks: int) -> bool:
    """Check if deploy artifact requirements are relevant for this task."""
    deploy_keywords = ("dockerfile", "docker", "deploy", "ci/cd", "workflow", "github actions", "production")
    lowered = task_text.lower()
    if any(kw in lowered for kw in deploy_keywords):
        return True
    # Show deploy requirements for the last 3 tasks
    if total_tasks > 0 and completed_tasks >= total_tasks - 3:
        return True
    return False


def _build_cline_prompt(
    *,
    project_name: str,
    intake_text: str,
    active_task_id: str,
    task_text: str,
    task_contract: dict,
    stack_config: dict,
    rules_text: str,
    preview_port: int,
    task_attempt_count: int,
    task_validation_result: dict,
    validation_command_results: list | None = None,
    completed_tasks: int = 0,
    total_tasks: int = 0,
) -> str:
    """Assemble the builder prompt from composable sections.

    Only injects stack-specific rules that are relevant to the current project.
    Deploy artifact requirements are shown only for deploy-related or late-stage tasks.
    Retry instructions are added when task_attempt_count > 0.
    """
    stack_identifier = str(stack_config.get("stack", "") or "").lower()
    framework = str(stack_config.get("framework", "") or "").lower()

    # Load the persistent builder identity from file
    try:
        builder_system_prompt = load_prompt("builder", "v1")
    except FileNotFoundError:
        builder_system_prompt = _PROMPT_HEADER

    sections = [
        builder_system_prompt,
        "",
        "---",
        "",
        f"PROJECT NAME:\n{project_name}\n",
        f"PROJECT INTAKE:\n{intake_text}\n",
        f"TASK ID:\n{active_task_id}\n",
        f"CURRENT TASK:\n{task_text}\n",
        f"TASK CONTRACT:\n{json.dumps(task_contract, indent=2, ensure_ascii=True)}\n",
        f"STACK CONFIG:\n{json.dumps(stack_config, indent=2, ensure_ascii=True)}\n",
        f"GLOBAL RULES:\n{rules_text}\n",
    ]

    # Mandatory verification steps from the task contract
    validation_commands = task_contract.get("validation_commands", [])
    if validation_commands:
        verification_lines = [
            "VERIFICATION STEPS (MANDATORY):",
            "Before reporting completion, you MUST run these commands and fix any errors:",
        ]
        for i, cmd in enumerate(validation_commands, 1):
            verification_lines.append(f"  {i}. {cmd}")
        verification_lines.append(
            "If any command fails, fix the issue and re-run until it passes."
        )
        verification_lines.append(
            "The orchestrator will run these same commands after you finish. "
            "If they fail, you will be sent back to fix the errors."
        )
        sections.append("\n".join(verification_lines) + "\n")

    # Validation command failure output from fast retries
    failed_commands = [
        r for r in (validation_command_results or []) if r.get("exit_code", 0) != 0
    ]
    if failed_commands:
        sections.append("VALIDATION COMMAND FAILURES (from previous attempt):\n")
        for r in failed_commands:
            sections.append(f"Command: {r['command']}")
            sections.append(f"Exit code: {r['exit_code']}")
            sections.append(f"Output:\n```\n{r['output'][-2000:]}\n```\n")
        sections.append(
            "Fix these specific errors. Do not redo other work. "
            "Focus ONLY on making these commands pass.\n"
        )

    # Retry-specific instructions
    if task_attempt_count > 0:
        checks = task_validation_result.get("checks", [])
        failure_details = "\n".join(
            f"- [{c.get('code', '?')}] {c.get('message', 'Unknown issue')}"
            for c in checks
        ) if checks else "- See LAST VALIDATION RESULT below for details"
        sections.append(
            f"RETRY INSTRUCTIONS (attempt {task_attempt_count + 1}):\n"
            f"The previous attempt failed validation. Focus specifically on fixing:\n"
            f"{failure_details}\n"
            f"Do not redo work that already succeeded. Fix only what is broken.\n"
        )

    sections.append(f"CURRENT TASK ATTEMPT:\n{task_attempt_count}\n")
    sections.append(f"LAST VALIDATION RESULT:\n{json.dumps(task_validation_result, indent=2, ensure_ascii=True)}\n")

    # Deploy artifact requirements — only for relevant tasks
    if _is_deploy_relevant_task(task_text, completed_tasks, total_tasks):
        sections.append("DEPLOY REQUIREMENTS:\n")
        sections.append(_PROMPT_DEPLOY_ARTIFACTS)

    sections.append(f"- The active preview port is {preview_port}\n")

    # Stack-specific rules — only injected when relevant
    if "next" in stack_identifier or "next" in framework:
        sections.append(_PROMPT_NEXTJS_RULES)
    if "prisma" in stack_identifier or "prisma" in framework:
        sections.append(_PROMPT_PRISMA_RULES)

    sections.append("UNIVERSAL RULES:\n")
    sections.append(_PROMPT_UNIVERSAL_RULES)

    return "\n".join(sections)


async def builder_node(state: AutomatronState) -> dict:
    """Run the current task in the project container."""
    container_id = state.get("container_id", "")
    task_text = state.get("current_task_text", "")
    task_index = state.get("current_task_index", -1)
    plan_md = state.get("plan_md", "")
    llm_config = normalize_llm_config(state.get("llm_config") or default_llm_config())
    builder_model_name = llm_config["builder"]["model"]
    project_name = state.get("project_name", "Automatron Project")
    intake_text = state.get("intake_text", "")

    if not container_id:
        return {
            "builder_status": "BLOCKER",
            "builder_error_detail": "No Docker container available",
            "builder_output": "",
            "project_stage": "building",
            "status": "building",
        }
    if not task_text:
        return {
            "builder_status": "BLOCKER",
            "builder_error_detail": "No task text provided",
            "builder_output": "",
            "project_stage": "building",
            "status": "building",
        }

    global_rules = get_global_rules(plan_md)
    rules_text = "\n".join(f"- {rule}" for rule in global_rules) if global_rules else "- None"
    stack_config = state.get("stack_config", {})
    preview_port = state.get("container_port", 3000)
    execution_contract = normalize_execution_contract(state.get("execution_contract") or {})
    active_task_id = state.get("active_task_id", f"task-{task_index + 1:03d}")
    task_contract = next(
        (task for task in execution_contract.get("task_graph", []) if task.get("task_id") == active_task_id),
        {},
    )

    completed_tasks, total_tasks = count_contract_progress(execution_contract)

    cline_prompt = _build_cline_prompt(
        project_name=project_name,
        intake_text=intake_text,
        active_task_id=active_task_id,
        task_text=task_text,
        task_contract=task_contract,
        stack_config=stack_config,
        rules_text=rules_text,
        preview_port=preview_port,
        task_attempt_count=int(state.get("task_attempt_count", 0) or 0),
        task_validation_result=state.get("task_validation_result", {}),
        validation_command_results=state.get("validation_command_results") or [],
        completed_tasks=completed_tasks,
        total_tasks=total_tasks,
    )

    try:
        await trace_event(
            state["project_id"],
            "builder",
            "builder.task.started",
            {
                "task_id": active_task_id,
                "task_index": task_index,
                "task_attempt_count": int(state.get("task_attempt_count", 0) or 0),
                "validation_commands": task_contract.get("validation_commands", []),
                "prompt": cline_prompt,
            },
            session_id=state.get("session_id"),
            stage=state.get("project_stage"),
        )
        await container_manager.copy_file_to_container(container_id, plan_md, "/workspace/PLAN.md")
        await container_manager.copy_file_to_container(
            container_id,
            cline_prompt,
            "/tmp/automatron_task_prompt.txt",
        )
    except Exception as exc:
        return {
            "builder_status": "BLOCKER",
            "builder_output": str(exc),
            "builder_error_detail": f"Failed to prepare Cline prompt: {exc}",
            "project_stage": "building",
            "status": "building",
        }

    model = shlex.quote(builder_model_name)
    timeout = settings.builder_cline_timeout
    shell_guards = (
        "AUTOMATRON_ALLOW_DEV_SERVER=0; "
        'next(){ if [ "${1:-}" = "dev" ] && [ "${AUTOMATRON_ALLOW_DEV_SERVER:-0}" != "1" ]; then '
        'echo "[Automatron] next dev is reserved for preview stage"; return 97; fi; command next "$@"; }; '
        'npm(){ if [ "${1:-}" = "run" ] && [ "${2:-}" = "dev" ] && [ "${AUTOMATRON_ALLOW_DEV_SERVER:-0}" != "1" ]; then '
        'echo "[Automatron] npm run dev is reserved for preview stage"; return 97; fi; command npm "$@"; }; '
        'pnpm(){ if [ "${1:-}" = "dev" ] && [ "${AUTOMATRON_ALLOW_DEV_SERVER:-0}" != "1" ]; then '
        'echo "[Automatron] pnpm dev is reserved for preview stage"; return 97; fi; command pnpm "$@"; }; '
        'yarn(){ if [ "${1:-}" = "dev" ] && [ "${AUTOMATRON_ALLOW_DEV_SERVER:-0}" != "1" ]; then '
        'echo "[Automatron] yarn dev is reserved for preview stage"; return 97; fi; command yarn "$@"; }; '
        "export -f next npm pnpm yarn; "
    )
    command = (
        f"{shell_guards}"
        f"PROMPT=$(cat /tmp/automatron_task_prompt.txt) && "
        f"cline task -y --json -m {model} -t {timeout} "
        '--cwd /workspace "$PROMPT"'
    )

    started = time.monotonic()
    try:
        result = await container_manager.exec_in_container(container_id, command, timeout=timeout + 30)
        output = result.output
        exit_code = result.exit_code
    except Exception as exc:
        return {
            "builder_status": "BLOCKER",
            "builder_output": str(exc),
            "builder_error_detail": f"Cline execution failed: {exc}",
            "builder_duration_s": time.monotonic() - started,
            "project_stage": "building",
            "status": "building",
        }

    updated_plan = plan_md
    try:
        updated_plan = await container_manager.read_file_from_container(container_id, "/workspace/PLAN.md")
    except Exception as exc:
        logger.warning("Could not read PLAN.md after task %d: %s", task_index, exc)

    touched_files: list[str] = []
    try:
        touched_result = await container_manager.exec_in_container(
            container_id,
            "cd /workspace && git status --porcelain --untracked-files=all",
            timeout=20,
        )
        if touched_result.exit_code == 0:
            touched_files = [
                line[3:].strip()
                for line in touched_result.output.splitlines()
                if len(line) > 3
            ]
    except Exception as exc:
        logger.warning("Could not read touched files after task %d: %s", task_index, exc)

    await trace_event(
        state["project_id"],
        "builder",
        "builder.task.completed",
        {
            "task_id": active_task_id,
            "task_index": task_index,
            "exit_code": exit_code,
            "duration_s": time.monotonic() - started,
            "files_touched": touched_files,
            "output": output,
        },
        session_id=state.get("session_id"),
        stage="building",
    )

    return {
        "builder_output": output,
        "builder_error_detail": "" if exit_code == 0 else output[-2000:],
        "builder_exit_code": exit_code,
        "builder_duration_s": time.monotonic() - started,
        "plan_md": updated_plan,
        "builder_report": {
            "task_id": active_task_id,
            "status": "completed" if exit_code == 0 else "failed",
            "commands_run": [command],
            "files_touched": touched_files,
            "validation_summary": {},
            "issues": [],
            "needs_escalation": False,
        },
        "project_stage": "building",
        "status": "building",
    }
