"""GitHub and git operations for generated project repositories."""

from __future__ import annotations

import base64
import logging
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import httpx

from orchestrator.config import settings
from orchestrator.github_actions.manager import GitHubActionsManager
from orchestrator.validation.workspace import StackValidatorResult, validate_workspace_contract

logger = logging.getLogger(__name__)

DEFAULT_BRANCH = "main"
DEVELOP_BRANCH = "develop"


@dataclass
class RepoMetadata:
    repo_name: str
    repo_url: str
    repo_clone_url: str
    default_branch: str = DEFAULT_BRANCH
    develop_branch: str = DEVELOP_BRANCH
    feature_branch: str = ""


class RepositoryManager:
    """Handles GitHub repo provisioning and workspace git operations."""

    def __init__(self) -> None:
        self.workspace_root = settings.workspace_base_dir
        self.actions_manager = GitHubActionsManager()

    def workspace_path(self, project_id: str) -> Path:
        path = self.workspace_root / project_id
        path.mkdir(parents=True, exist_ok=True)
        return path

    def create_feature_branch_name(self, project_name: str, run_seq: int = 1) -> str:
        slug = _slugify(project_name) or "project"
        return f"feature/{run_seq}-{slug[:48]}"

    async def create_remote_repository(self, project_id: str, project_name: str) -> RepoMetadata:
        if not settings.github_token:
            raise RuntimeError("GITHUB_TOKEN is required to create remote repositories")

        repo_name = f"{_slugify(project_name) or 'project'}-{project_id[:8]}"
        feature_branch = self.create_feature_branch_name(project_name)

        existing = await self._get_repository(repo_name)
        if existing:
            return RepoMetadata(
                repo_name=repo_name,
                repo_url=existing["html_url"],
                repo_clone_url=existing["clone_url"],
                feature_branch=feature_branch,
            )

        endpoint = "/user/repos"
        if settings.github_owner_type == "org" and settings.github_owner:
            endpoint = f"/orgs/{settings.github_owner}/repos"

        payload = {
            "name": repo_name,
            "private": settings.github_repo_visibility != "public",
            "auto_init": False,
            "description": f"Generated by Automatron for project {project_name}",
        }

        async with httpx.AsyncClient(
            base_url=settings.github_api_url,
            headers=self._github_headers(),
            timeout=30,
        ) as client:
            response = await client.post(endpoint, json=payload)
            if response.status_code not in {201, 422}:
                raise RuntimeError(
                    f"GitHub repository creation failed: {response.status_code} {response.text}"
                )
            if response.status_code == 422:
                existing = await self._get_repository(repo_name)
                if existing is None:
                    raise RuntimeError(
                        "GitHub returned 422 while creating repository, and no existing repo was found"
                    )
                data = existing
            else:
                data = response.json()

        return RepoMetadata(
            repo_name=repo_name,
            repo_url=data["html_url"],
            repo_clone_url=data["clone_url"],
            feature_branch=feature_branch,
        )

    async def ensure_remote_cicd(self, metadata: RepoMetadata) -> None:
        await self.actions_manager.ensure_environment(
            metadata.repo_name,
            environment_name=settings.github_environment_name,
        )

    async def configure_remote_cicd_for_target(
        self,
        repo_name: str,
        deploy_target: dict[str, Any],
    ) -> list[str]:
        await self.actions_manager.ensure_environment(
            repo_name,
            environment_name=settings.github_environment_name,
        )
        return await self.actions_manager.upsert_environment_secrets(
            repo_name,
            deploy_target,
            environment_name=settings.github_environment_name,
        )

    async def sync_remote_cicd_status(
        self,
        repo_name: str,
        *,
        feature_branch: str = "",
        develop_branch: str = DEVELOP_BRANCH,
        default_branch: str = DEFAULT_BRANCH,
    ) -> dict[str, Any]:
        return await self.actions_manager.sync_repository(
            repo_name,
            feature_branch=feature_branch,
            develop_branch=develop_branch,
            default_branch=default_branch,
        )

    async def _get_repository(self, repo_name: str) -> dict[str, Any] | None:
        if not settings.github_owner:
            return None

        async with httpx.AsyncClient(
            base_url=settings.github_api_url,
            headers=self._github_headers(),
            timeout=15,
        ) as client:
            response = await client.get(f"/repos/{settings.github_owner}/{repo_name}")
            if response.status_code == 404:
                return None
            response.raise_for_status()
            return response.json()

    async def get_remote_repository(self, repo_name: str) -> dict[str, Any] | None:
        return await self._get_repository(repo_name)

    async def delete_remote_repository(self, repo_name: str) -> bool:
        existing = await self._get_repository(repo_name)
        if existing is None:
            return False

        async with httpx.AsyncClient(
            base_url=settings.github_api_url,
            headers=self._github_headers(),
            timeout=30,
        ) as client:
            response = await client.delete(f"/repos/{settings.github_owner}/{repo_name}")
            if response.status_code not in {204, 404}:
                raise RuntimeError(
                    f"GitHub repository deletion failed: {response.status_code} {response.text}"
                )
        return response.status_code == 204

    def initialize_workspace_repository(
        self,
        project_id: str,
        project_name: str,
        metadata: RepoMetadata,
    ) -> None:
        workspace = self.workspace_path(project_id)
        self._ensure_gitignore(workspace)
        self._git(workspace, ["init"])
        self._git(workspace, ["config", "user.name", settings.git_author_name])
        self._git(workspace, ["config", "user.email", settings.git_author_email])
        self._git(workspace, ["branch", "-M", metadata.default_branch])

        remotes = self._git(workspace, ["remote"], check=False)
        if "origin" in remotes.stdout.split():
            self._git(workspace, ["remote", "remove", "origin"])
        self._git(workspace, ["remote", "add", "origin", metadata.repo_clone_url])

        self._git(workspace, ["add", "-A"])
        self._git(
            workspace,
            ["commit", "--allow-empty", "-m", f"chore: bootstrap {project_name}"],
            check=False,
        )
        self._git(workspace, ["push", "-u", "origin", metadata.default_branch], authenticated=True)

        self._git(workspace, ["checkout", "-B", metadata.develop_branch])
        self._git(workspace, ["push", "-u", "origin", metadata.develop_branch], authenticated=True)

        self._git(workspace, ["checkout", "-B", metadata.feature_branch])
        self._git(workspace, ["push", "-u", "origin", metadata.feature_branch], authenticated=True)

    def commit_workspace_changes(
        self,
        project_id: str,
        message: str,
        branch: str | None = None,
    ) -> str | None:
        workspace = self.workspace_path(project_id)
        self._git(workspace, ["add", "-A"])
        status = self._git(workspace, ["status", "--porcelain"])
        if not status.stdout.strip():
            return None

        self._git(workspace, ["commit", "-m", message])
        active_branch = branch or self.current_branch(project_id)
        self._git(workspace, ["push", "origin", active_branch], authenticated=True)
        sha = self._git(workspace, ["rev-parse", "HEAD"]).stdout.strip()
        return sha or None

    def current_branch(self, project_id: str) -> str:
        workspace = self.workspace_path(project_id)
        return self._git(workspace, ["branch", "--show-current"]).stdout.strip()

    def merge_branch(
        self,
        project_id: str,
        source_branch: str,
        target_branch: str,
        message: str,
    ) -> str:
        workspace = self.workspace_path(project_id)

        self._git(workspace, ["fetch", "origin"], authenticated=True)
        self._git(workspace, ["checkout", target_branch], check=False)
        current = self.current_branch(project_id)
        if current != target_branch:
            self._git(workspace, ["checkout", "-B", target_branch, f"origin/{target_branch}"])
        self._git(workspace, ["pull", "origin", target_branch], authenticated=True)
        self._git(workspace, ["merge", "--no-ff", source_branch, "-m", message])
        self._git(workspace, ["push", "origin", target_branch], authenticated=True)
        sha = self._git(workspace, ["rev-parse", "HEAD"]).stdout.strip()
        self._git(workspace, ["checkout", source_branch], check=False)
        return sha

    def validate_deploy_artifacts(
        self,
        project_id: str,
        *,
        stack_config: dict[str, Any] | None = None,
        container_manager: Any | None = None,
        container_id: str | None = None,
        require_heavy_checks: bool = False,
    ) -> StackValidatorResult:
        workspace = self.workspace_path(project_id)
        return validate_workspace_contract(
            workspace,
            stack_config=stack_config,
        )

    def ensure_deploy_supporting_docs(self, project_id: str, project_name: str) -> None:
        workspace = self.workspace_path(project_id)
        env_file = workspace / ".env.example"
        if not env_file.exists():
            env_file.write_text("APP_PORT=3000\n", encoding="utf-8")

        deploy_dir = workspace / "deploy"
        deploy_dir.mkdir(parents=True, exist_ok=True)

        compose_file = deploy_dir / "docker-compose.yml"
        if not compose_file.exists():
            compose_file.write_text(
                """services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    env_file:
      - ../.env
    ports:
      - "${APP_PORT:-3000}:3000"
""",
                encoding="utf-8",
            )

        deploy_md = workspace / "DEPLOY.md"
        deploy_md.write_text(
            (
                f"# Deploy {project_name}\n\n"
                "This project is deployed by GitHub Actions using the `production` environment.\n"
                "The release workflow uploads the repository to the VPS and runs "
                "`docker compose -f deploy/docker-compose.yml up -d --build`.\n\n"
                "Recommended application health check path: `/api/health`.\n"
            ),
            encoding="utf-8",
        )

        workflows_dir = workspace / ".github" / "workflows"
        workflows_dir.mkdir(parents=True, exist_ok=True)
        for relative_path, content in self.actions_manager.workflow_files().items():
            workflow_path = workspace / relative_path
            workflow_path.parent.mkdir(parents=True, exist_ok=True)
            workflow_path.write_text(content, encoding="utf-8")

    def _ensure_gitignore(self, workspace: Path) -> None:
        gitignore = workspace / ".gitignore"
        existing = gitignore.read_text(encoding="utf-8") if gitignore.exists() else ""
        required_entries = ["node_modules/", "__pycache__/", ".env", ".venv/", ".next/", "dist/"]
        lines = [line.strip() for line in existing.splitlines() if line.strip()]
        updated = False
        for entry in required_entries:
            if entry not in lines:
                lines.append(entry)
                updated = True
        if updated or not gitignore.exists():
            gitignore.write_text("\n".join(lines) + "\n", encoding="utf-8")

    def _git(
        self,
        cwd: Path,
        args: list[str],
        *,
        authenticated: bool = False,
        check: bool = True,
    ) -> subprocess.CompletedProcess[str]:
        command = ["git"]
        if authenticated and settings.github_token:
            command.extend(["-c", f"http.extraHeader={self._git_auth_header()}"])
        command.extend(args)

        result = subprocess.run(
            command,
            cwd=cwd,
            text=True,
            capture_output=True,
            check=False,
        )
        if check and result.returncode != 0:
            raise RuntimeError(
                f"Git command failed ({' '.join(command)}): {result.stdout}\n{result.stderr}"
            )
        return result

    def _github_headers(self) -> dict[str, str]:
        headers = {
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
        }
        if settings.github_token:
            headers["Authorization"] = f"Bearer {settings.github_token}"
        return headers

    def _git_auth_header(self) -> str:
        token = base64.b64encode(f"x-access-token:{settings.github_token}".encode("utf-8")).decode(
            "ascii"
        )
        return f"Authorization: Basic {token}"


def _slugify(value: str) -> str:
    value = value.lower()
    value = re.sub(r"[^a-z0-9]+", "-", value)
    return value.strip("-")
