"""Tests for structured workspace validation."""

from __future__ import annotations

import pytest

from orchestrator.docker_engine.manager import ExecResult
from orchestrator.validation.workspace import (
    should_validate_release_artifacts,
    validate_workspace_contract,
    validate_workspace_contract_async,
)


def _write_valid_nextjs_workspace(workspace):
    (workspace / "deploy").mkdir(parents=True, exist_ok=True)
    (workspace / ".github" / "workflows").mkdir(parents=True, exist_ok=True)
    (workspace / "app" / "api" / "health").mkdir(parents=True, exist_ok=True)
    (workspace / "prisma").mkdir(parents=True, exist_ok=True)

    (workspace / "next.config.ts").write_text("export default {};\n", encoding="utf-8")
    (workspace / "package-lock.json").write_text("{}\n", encoding="utf-8")
    (workspace / "Dockerfile").write_text("FROM node:22\nCMD [\"npm\", \"run\", \"start\"]\n", encoding="utf-8")
    (workspace / ".env.example").write_text("APP_PORT=3000\n", encoding="utf-8")
    (workspace / "deploy" / "docker-compose.yml").write_text(
        "services:\n  app:\n    build:\n      context: ..\n      dockerfile: Dockerfile\n",
        encoding="utf-8",
    )
    (workspace / "DEPLOY.md").write_text(
        "docker compose -f deploy/docker-compose.yml up -d --build\n",
        encoding="utf-8",
    )
    (workspace / ".github" / "workflows" / "ci.yml").write_text(
        "on:\n  push:\n    branches:\n      - \"feature/**\"\n      - develop\n",
        encoding="utf-8",
    )
    (workspace / ".github" / "workflows" / "deploy.yml").write_text(
        "on:\n  push:\n    branches:\n      - main\nenvironment: production\n",
        encoding="utf-8",
    )
    (workspace / "app" / "layout.tsx").write_text(
        "export const metadata = { title: 'Invoice Dashboard', description: 'Custom app' };\n",
        encoding="utf-8",
    )
    (workspace / "app" / "api" / "health" / "route.ts").write_text(
        "export async function GET() { return Response.json({ status: 'ok', service: 'invoice-dashboard', timestamp: new Date().toISOString() }); }\n",
        encoding="utf-8",
    )
    (workspace / "prisma" / "schema.prisma").write_text(
        "datasource db { provider = \"sqlite\" url = \"file:./dev.db\" }\n generator client { provider = \"prisma-client-js\" }\n model Invoice { id String @id }\n",
        encoding="utf-8",
    )


def test_validate_workspace_contract_flags_default_metadata_and_missing_health(tmp_path):
    workspace = tmp_path
    (workspace / "app").mkdir(parents=True, exist_ok=True)
    (workspace / "deploy").mkdir(parents=True, exist_ok=True)
    (workspace / ".github" / "workflows").mkdir(parents=True, exist_ok=True)
    (workspace / "next.config.ts").write_text("export default {};\n", encoding="utf-8")
    (workspace / "Dockerfile").write_text("FROM node:22\nCMD [\"npm\", \"run\", \"start\"]\n", encoding="utf-8")
    (workspace / ".env.example").write_text("APP_PORT=3000\n", encoding="utf-8")
    (workspace / "deploy" / "docker-compose.yml").write_text(
        "services:\n  app:\n    build: .\n",
        encoding="utf-8",
    )
    (workspace / "DEPLOY.md").write_text(
        "docker compose -f deploy/docker-compose.yml up -d --build\n",
        encoding="utf-8",
    )
    (workspace / ".github" / "workflows" / "ci.yml").write_text(
        "develop\nfeature/**\n",
        encoding="utf-8",
    )
    (workspace / ".github" / "workflows" / "deploy.yml").write_text(
        "main\nenvironment: production\n",
        encoding="utf-8",
    )
    (workspace / "app" / "layout.tsx").write_text(
        "export const metadata = { title: 'Create Next App', description: 'Generated by create next app' };\n",
        encoding="utf-8",
    )

    result = validate_workspace_contract(workspace, stack_config={"framework": "nextjs"})
    codes = {issue.code for issue in result.blocking_issues}

    assert "stack_next_health_missing" in codes
    assert "stack_next_default_metadata" in codes
    assert result.runtime_spec is not None
    assert result.runtime_spec.readiness_path == "/api/health"


def test_validate_workspace_contract_can_skip_release_artifact_gates(tmp_path):
    workspace = tmp_path
    (workspace / "app" / "api" / "health").mkdir(parents=True, exist_ok=True)
    (workspace / "prisma").mkdir(parents=True, exist_ok=True)
    (workspace / "next.config.ts").write_text("export default {};\n", encoding="utf-8")
    (workspace / "app" / "layout.tsx").write_text(
        "export const metadata = { title: 'Invoice Dashboard', description: 'Custom app' };\n",
        encoding="utf-8",
    )
    (workspace / "app" / "api" / "health" / "route.ts").write_text(
        "export async function GET() { return Response.json({ status: 'ok', service: 'invoice-dashboard', timestamp: new Date().toISOString() }); }\n",
        encoding="utf-8",
    )
    (workspace / "prisma" / "schema.prisma").write_text(
        "datasource db { provider = \"sqlite\" url = \"file:./dev.db\" }\n generator client { provider = \"prisma-client-js\" }\n model Invoice { id String @id }\n",
        encoding="utf-8",
    )

    result = validate_workspace_contract(
        workspace,
        stack_config={"framework": "nextjs", "database": "prisma"},
        include_release_artifacts=False,
    )

    codes = {issue.code for issue in result.blocking_issues}
    assert "artifact_dockerfile_missing" not in codes
    assert "artifact_deploy_compose_missing" not in codes
    assert result.ok


def test_should_validate_release_artifacts_only_on_late_or_deploy_tasks():
    assert not should_validate_release_artifacts(
        "Verify and adapt scaffold",
        completed_tasks=0,
        total_tasks=10,
    )
    assert should_validate_release_artifacts(
        "Create Dockerfile",
        completed_tasks=1,
        total_tasks=10,
    )
    assert should_validate_release_artifacts(
        "Implement final page polish",
        completed_tasks=8,
        total_tasks=10,
    )


@pytest.mark.asyncio
async def test_validate_workspace_contract_async_runs_heavy_checks(tmp_path):
    workspace = tmp_path
    _write_valid_nextjs_workspace(workspace)

    class _FakeContainerManager:
        async def exec_in_container(self, container_id: str, command: str, timeout: int = 300) -> ExecResult:
            if "npm run build" in command:
                return ExecResult(exit_code=1, output="build failed")
            if "@prisma/client" in command:
                return ExecResult(exit_code=1, output="prisma import failed")
            return ExecResult(exit_code=0, output="")

    result = await validate_workspace_contract_async(
        workspace,
        stack_config={"framework": "nextjs", "database": "prisma"},
        container_manager=_FakeContainerManager(),
        container_id="container-1",
        require_heavy_checks=True,
    )

    codes = {issue.code for issue in result.blocking_issues}
    assert "heavy_build_failed" in codes
    assert "heavy_prisma_import_failed" in codes
