"""ArtifactPusher — pushes deploy artifacts into the child repo.

Two modes:
- `pr` (default): create branch + push files + open PR for review
- `direct`: push directly onto the default branch
"""

from __future__ import annotations

import logging
from typing import Any

import httpx

from orchestrator.config import settings
from orchestrator.deployment_v2.profile import ArtifactFingerprint, DeploymentProfile
from orchestrator.deployment_v2.templates import TEMPLATES_VERSION
from orchestrator.github.issues import GitHubClient

logger = logging.getLogger(__name__)

DEFAULT_PR_BRANCH = "chore/automatron-deploy-artifacts"
DEFAULT_PR_TITLE = "chore: configure Kamal deployment artifacts"
DEFAULT_PR_BODY = (
    "This PR was generated by **Automatron** and contains the deterministic "
    "deployment artifacts (Dockerfile, Kamal config, GitHub Actions workflows).\n\n"
    "These files are owned by Automatron templates. Do not edit by hand — re-run "
    "*Generate artifacts* in Automatron to regenerate them.\n\n"
    "After merge, Automatron can trigger production deployments via "
    "`workflow_dispatch` on the *Deploy* workflow."
)


class ArtifactPusher:
    def __init__(
        self,
        client: GitHubClient | None = None,
        *,
        strategy_version: str,
    ) -> None:
        self._client = client or GitHubClient()
        self._strategy_version = strategy_version

    async def push(
        self,
        *,
        owner: str,
        repo: str,
        profile: DeploymentProfile,
        files: dict[str, str],
        mode: str = "pr",
        base_branch: str = "main",
        branch_name: str = DEFAULT_PR_BRANCH,
    ) -> ArtifactFingerprint:
        if mode == "pr":
            return await self._push_via_pr(
                owner=owner,
                repo=repo,
                profile=profile,
                files=files,
                base_branch=base_branch,
                branch_name=branch_name,
            )
        if mode == "direct":
            return await self._push_direct(
                owner=owner,
                repo=repo,
                profile=profile,
                files=files,
                branch=base_branch,
            )
        raise ValueError(f"Unknown artifacts_push_mode: {mode!r}")

    async def _push_direct(
        self,
        *,
        owner: str,
        repo: str,
        profile: DeploymentProfile,
        files: dict[str, str],
        branch: str,
    ) -> ArtifactFingerprint:
        for path, content in files.items():
            await self._client.push_file(
                owner,
                repo,
                path,
                content,
                commit_message=f"chore(deploy): update {path}",
                branch=branch,
            )
        head_sha = await self._get_branch_sha(owner, repo, branch)
        return ArtifactFingerprint(
            commit_sha=head_sha or "",
            branch=branch,
            pr_url=None,
            template_version=TEMPLATES_VERSION,
            strategy_version=self._strategy_version,
            profile_hash=profile.hash(),
            rendered_files=sorted(files),
        )

    async def _push_via_pr(
        self,
        *,
        owner: str,
        repo: str,
        profile: DeploymentProfile,
        files: dict[str, str],
        base_branch: str,
        branch_name: str,
    ) -> ArtifactFingerprint:
        base_sha = await self._get_branch_sha(owner, repo, base_branch)
        if not base_sha:
            raise RuntimeError(f"Cannot resolve SHA of base branch {base_branch!r}")

        await self._ensure_branch(owner, repo, branch_name, base_sha)

        for path, content in files.items():
            await self._client.push_file(
                owner,
                repo,
                path,
                content,
                commit_message=f"chore(deploy): update {path}",
                branch=branch_name,
            )

        pr_url = await self._open_or_get_pr(
            owner=owner,
            repo=repo,
            head=branch_name,
            base=base_branch,
        )

        head_sha = await self._get_branch_sha(owner, repo, branch_name)
        return ArtifactFingerprint(
            commit_sha=head_sha or "",
            branch=branch_name,
            pr_url=pr_url,
            template_version=TEMPLATES_VERSION,
            strategy_version=self._strategy_version,
            profile_hash=profile.hash(),
            rendered_files=sorted(files),
        )

    async def _get_branch_sha(self, owner: str, repo: str, branch: str) -> str | None:
        async with self._http_client() as client:
            response = await client.get(f"/repos/{owner}/{repo}/branches/{branch}")
            if response.status_code == 404:
                return None
            response.raise_for_status()
            data = response.json()
            return ((data.get("commit") or {}).get("sha")) or None

    async def _ensure_branch(
        self,
        owner: str,
        repo: str,
        branch: str,
        from_sha: str,
    ) -> None:
        async with self._http_client() as client:
            existing = await client.get(
                f"/repos/{owner}/{repo}/git/ref/heads/{branch}"
            )
            if existing.status_code == 200:
                logger.info("Branch %s already exists in %s/%s", branch, owner, repo)
                return
            if existing.status_code != 404:
                existing.raise_for_status()

            response = await client.post(
                f"/repos/{owner}/{repo}/git/refs",
                json={"ref": f"refs/heads/{branch}", "sha": from_sha},
            )
            if response.status_code not in {200, 201}:
                raise RuntimeError(
                    f"Failed to create branch {branch} in {owner}/{repo}: "
                    f"{response.status_code} {response.text}"
                )

    async def _open_or_get_pr(
        self,
        *,
        owner: str,
        repo: str,
        head: str,
        base: str,
    ) -> str | None:
        async with self._http_client() as client:
            existing = await client.get(
                f"/repos/{owner}/{repo}/pulls",
                params={"head": f"{owner}:{head}", "state": "open"},
            )
            existing.raise_for_status()
            existing_prs = existing.json()
            if existing_prs:
                return existing_prs[0].get("html_url")

            response = await client.post(
                f"/repos/{owner}/{repo}/pulls",
                json={
                    "title": DEFAULT_PR_TITLE,
                    "body": DEFAULT_PR_BODY,
                    "head": head,
                    "base": base,
                },
            )
            if response.status_code not in {200, 201}:
                raise RuntimeError(
                    f"Failed to open PR {head}->{base} in {owner}/{repo}: "
                    f"{response.status_code} {response.text}"
                )
            return response.json().get("html_url")

    def _http_client(self) -> httpx.AsyncClient:
        headers = {
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
        }
        if settings.github_token:
            headers["Authorization"] = f"Bearer {settings.github_token}"
        return httpx.AsyncClient(
            base_url=settings.github_api_url or "https://api.github.com",
            headers=headers,
            timeout=20.0,
        )
